# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Documentation
    url: docs/
    weight: 20
  - name: News
    url: blog/
    weight: 30
  - name: Other examples
    url: showcase/
    weight: 40
  - name: Events
    url: events/
    weight: 60

